### ISSUE TITLE
Documentation != Code

### ISSUE THREAD

**Issue by glaslos** [seiflotfy/count-min-log#3]
Your documentation seems ahead of the code base.

**Comment by seiflotfy** [comment]
it should be in sync now https://godoc.org/github.com/seiflotfy/count-min-log

**Comment by glaslos** [comment]
From the README I am missing `NewDefaultSketch8`, `NewDefaultSketch16` and `GetCount`. I used `NewDefaultSketch` and `Frequency` instead.

**Comment by seiflotfy** [comment]
I got rid of NewDefaultSketch8 and NewDefaultSketch16
Will update the docs

**Comment by glaslos** [comment]
See #4
